#pragma once

#include <Windows.h>  
#include <d3d9.h>
#include <d3dx9.h>
#include <map>
#include "debug.h" 

#include <fstream> 
#include <string>
#include <stdio.h>
#include <iostream>
#include <algorithm>
#include <stdlib.h>
#include <iomanip>
#include <vector>
#include <iostream>

#define WIN_NAME L"NewbieGame"
#define WIN_TITLE L"NewbieGame"

#define BGColor D3DCOLOR_XRGB(255,255,200)
#define BGColorCrossing D3DCOLOR_XRGB(255,255,200)
#define SCREEN_WIDTH 525	//530
#define SCREEN_HEIGHT 490	//480
#define BOTTOM_SCREEN 450

#define MaxFrameRate 100	//default Frame Rate is the truth

#define SCENEGAME_GAMETIMEMAX		300

#define DIRECTINPUT_VERSION 0x0800
#define KEYBOARD_BUFFER_SIZE 1024

#define MAX_SCENE_LINE 1024

#define STAGE_1						500
#define STAGE_2_1					1000
#define STAGE_2_2					1500
#define STAGE_3_1					2000
#define STAGE_3_2					2500
#define STAGE_4						3000

#define STAGE_1_MAX_WIDTH			1250
#define STAGE_2_1_MAX_WIDTH			262
#define STAGE_2_2_MAX_WIDTH			776
#define STAGE_3_1_MAX_WIDTH			1282
#define STAGE_3_2_MAX_WIDTH			1282

#define SCENE_SECTION_UNKNOWN			-1
#define SCENE_SECTION_OBJECTS			1
#define SCENE_SECTION_TEXTURES			2
#define SCENE_SECTION_SPRITES			3
#define SCENE_SECTION_ANIMATIONS		4
#define SCENE_SECTION_ANIMATION_SETS	5
#define SCENE_SECTION_SCENEFILEPATH		6
#define SCENE_SECTION_TILEMAP			7
#define SCENE_SECTION_CLEARTEXTURES			8
#define SCENE_SECTION_CLEARSPRITES			9
#define SCENE_SECTION_CLEARANIMATIONS		10
#define SCENE_SECTION_CLEARANIMATION_SETS	11


#define ANIMATION_SET_BBOX					0
#define ANIMATION_SET_PLAYER				1
#define ANIMATION_SET_MS					2
#define ANIMATION_SET_DAGGER				3
#define ANIMATION_SET_BOOMERANG				4
#define ANIMATION_SET_AXE					5
#define ANIMATION_SET_WATERPOTION			6
#define ANIMATION_SET_BONE					9
#define ANIMATION_SET_BLACKBOARD			10
#define ANIMATION_SET_PLAYERHP				11
#define ANIMATION_SET_TEXTS					12
#define ANIMATIONS_SET_UIEXTRASHOT			13
#define ANIMATION_SET_BRICK					20
#define ANIMATION_SET_BREAKABLEBRICK		21
#define ANIMATION_SET_TORCH					22
#define ANIMATION_SET_CANDLE				23
#define ANIMATION_SET_MOVINGFLATFORM		24
#define ANIMATION_SET_STAIRS				25
#define ANIMATION_SET_GATE					26
#define ANIMATION_SET_BUSH					27
#define ANIMATION_SET_SMALLHEART			40
#define ANIMATION_SET_BIGHEART				41
#define ANIMATION_SET_CHICKENLEG			42
#define ANIMATION_SET_MONEYBAGS				43
#define ANIMATION_SET_BAGRED				44
#define ANIMATION_SET_BAGWHITE				45
#define ANIMATION_SET_BAGBLUE				46
#define ANIMATION_SET_UPGRADEMS				47
#define ANIMATION_SET_CRYSTALBALL			48
#define ANIMATION_SET_INVIPOTION			49
#define ANIMATION_SET_ITEMDAGGER			50
#define ANIMATION_SET_ITEMSTOPWATCH			51
#define ANIMATION_SET_CROSS					52
#define ANIMATION_SET_CROWN					53
#define ANIMATION_SET_ITEMEXTRASHOT			54
#define ANIMATION_SET_ITEMBMR				55
#define ANIMATION_SET_ITEMAXE				56
#define ANIMATION_SET_ITEMWATERPOTION		57
#define ANIMATION_SET_FIREEFFECT			70
#define ANIMATION_SET_HITEFFECT				71
#define ANIMATION_SET_BRICKEXPLODE			72
#define ANIMATION_SET_ADDSCORE				73
#define ANIMATION_SET_BAT					80
#define ANIMATION_SET_ZOMBIE				81
#define ANIMATION_SET_DARKENBAT				82
#define ANIMATION_SET_KNIGHT				83
#define ANIMATION_SET_GHOST					84
#define ANIMATION_SET_RAVEN					85
#define ANIMATION_SET_HUNCHMAN				86
#define ANIMATION_SET_SKELETON				87
#define ANIMATION_SET_TLEBAT				88
#define ANIMATION_SET_TITLESCENE			100
#define ANIMATION_SET_TITLEBAT				101
#define ANIMATION_SET_STARTTEXT				102
#define ANIMATION_SET_INTROSCENE			103
#define ANIMATION_SET_INTROSIMON			104
#define ANIMATION_SET_PLAYSCENE				105
#define ANIMATION_SET_MAPSTAGE1				106
#define ANIMATION_SET_MAPSTAGE2_1			107
#define ANIMATION_SET_MAPSTAGE2_2			108
#define ANIMATION_SET_MAPSTAGE3_1			109
#define ANIMATION_SET_MAPSTAGE3_2			110
#define ANIMATION_SET_ITEMPOKEBALL			-9
#define ANIMATION_SET_POKEBALL				-10

//Nen define thanh nhieu lop type
//Vd Zombie thuoc EntityType, EnemyType
enum EntityType
{
	//For Special Case
	NONE = -1,

	//Bounding Box
	BBOX = 0,

	//Player Zone 1-10
	PLAYER = 1,
	MORNINGSTAR = 2,
	DAGGER = 3,
	BOOMERANG = 4,
	AXE = 5,
	WATERPOTION = 6,
	STOPWATCH = 7,
	BONE = 9,

	//UI Zone 10-20
	BLACKBOARD = 10,
	PLAYERHP = 11,
	TEXTS = 12,
	UIEXTRASHOT = 13,

	//Static Obj Zone 20-40
	BRICK = 20,
	BREAKABLEBRICK = 21,
	TORCH = 22,
	CANDLE = 23,
	MOVINGPLATFORM = 24,
	STAIRS = 25,
	GATE = 26,
	BUSH = 27,

	//Item Zone 40-70
	SMALLHEART = 40,
	BIGHEART = 41,
	YUMMICHICKENLEG = 42,
	MONEYBAGS = 43,
	MONEYBAGRED = 44,
	MONEYBAGWHITE = 45,
	MONEYBAGBLUE = 46,
	UPGRADEMORNINGSTAR = 47,
	CRYSTALBALL = 48,
	INVIPOTION = 49,
	ITEMDAGGER = 50,
	ITEMSTOPWATCH = 51,
	CROSS = 52,
	CROWN = 53,
	ITEMEXTRASHOT = 54,
	ITEMBOOMERANG = 55,
	ITEMAXE = 56,
	ITEMWATERPOTION = 57,

	//Effect Zone 70-80
	FIREEFFECT = 70,
	HITEFFECT = 71,
	BRICKEXPLODEEFFECT = 72,
	ADDSCOREEFFECT = 73,

	//Enemies Zone 80-100
	BAT = 80,
	ZOMBIE = 81,
	DARKENBAT = 82,
	KNIGHT = 83,
	GHOST = 84,
	RAVEN = 85,
	HUNCHMAN = 86,
	SKELETON = 87,
	TLEBAT = 88,

	//Scene Zone 100-120
	TITLESCENE = 100,
	TITLEBAT = 101,
	STARTTEXT = 102,
	INTROSCENE = 103,
	INTROSIMON = 104,
	PLAYSCENE = 105,
	MAPSTAGE1 = 106,
	MAPSTAGE2_1 = 107,
	MAPSTAGE2_2 = 108,
	MAPSTAGE3_1 = 109,
	MAPSTAGE3_2 = 110,

	//Ex
	ITEMPOKEBALL = -9,
	POKEBALL = -10
};

class define
{
};

